#!/usr/bin/env node
'use strict';

// Build `dist/cli.js` — the entry point the published package ships.
//
// We use the "wrapper" approach: `dist/cli.js` is a tiny shim that requires
// the real `cli/index.js` from the source tree. We deliberately do NOT
// `esbuild --bundle` here. Bundling embeds all of `cli/lib/*` into a single
// file at `dist/cli.js`, but `cli/lib/target-download.js` and friends rely
// on `path.join(__dirname, '..', '..', 'templates.lock.json')` to resolve
// their config. After bundling, `__dirname` is the bundle's directory
// (`dist/`) and the relative paths stop pointing at the repo root.
//
// The wrapper keeps `__dirname` correct for the real source location, and
// it stays a single CLI file at the published entry point.

const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..');
const distDir = path.join(repoRoot, 'dist');
const cliSourceAbs = path.join(repoRoot, 'cli', 'index.js');

// Compute a POSIX-style relative path so `require('./...')` works on every
// platform. We require the relative path to start with `./` or `../` so the
// require is unambiguously local (not a node_modules lookup).
let rel = path.relative(distDir, cliSourceAbs).split(path.sep).join('/');
if (!rel.startsWith('.')) rel = './' + rel;

const wrapper =
  "#!/usr/bin/env node\n" +
  "'use strict';\n" +
  "\n" +
  "// Generated by scripts/build-cli.js — DO NOT EDIT BY HAND.\n" +
  "// This wrapper exists because bundling cli/ into a single file would\n" +
  "// break the `__dirname`-relative path lookups in cli/lib/ (e.g.\n" +
  "// templates.lock.json). Delegating to the real source keeps the\n" +
  "// require graph pointing at the original module locations.\n" +
  "require(" + JSON.stringify(rel) + ");\n";

fs.mkdirSync(distDir, { recursive: true });
const out = path.join(distDir, 'cli.js');
fs.writeFileSync(out, wrapper, { encoding: 'utf8' });
fs.chmodSync(out, 0o755);

process.stdout.write('Built ' + out + ' (wrapper -> ' + rel + ')\n');
